version: '3'

services:
  university_notification_service:
    build: .
    container_name: university_notification_service
    restart: on-failure
    command: bash -c "yarn && yarn start:$UNIVERSITY_SERVER_ARG"
    ports:
      - ${UNIVERSITY_SERVER_PORT}:${UNIVERSITY_SERVER_PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    networks:
      - notification-university-network
networks:
  notification-university-network:
